### ISSUE TITLE
normalization eigenvectors when computed using 'trick' 

### ISSUE THREAD

**Issue by aljevandam** [UtrechtUniversity/SCCA#24]
In SCCA_compute, when the eigenvalues are computed using the 'trick' (i.e. first doing decomposition of the 'small matrix'  to obtain the matrix of vectors U and then obtaining the eigenvectors by pre-multiplying with D^-1 A, so that D^-1 A U = V. This gives the correct eigenvectors but not normalized properly. They should be normalized by setting v = v / (v^T D v )  (where D is the appropriate diagonal matrix with either row or column sums on the diagonal)

**Comment by KvEijden** [comment]
Implemented
